name: Build and Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12.22
        uses: actions/setup-node@v1
        with:
          node-version: 12.22
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn run lint
      - name: Build
        run: yarn run build
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12.22
        uses: actions/setup-node@v1
        with:
          node-version: 12.22
      - name: Install Dependencies
        run: yarn
      - name: Semver Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Release Docker Container
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ steps.package-version.outputs.current-version}}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:latest
