name: Build and Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12.22
        uses: actions/setup-node@v1
        with:
          node-version: 12.22
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn run lint
      - name: Build
        run: yarn run build
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12.22
        uses: actions/setup-node@v1
        with:
          node-version: 12.22
      - name: Install Dependencies
        run: yarn
      - name: Semver Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Release Docker Container
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.repository }}/typescript-project-template
          tag_with_sha: true
          tag_with_ref: true