name: Node.js Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12.22
        uses: actions/setup-node@v1
        with:
          node-version: 12.22
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn run lint
      - name: Build
        run: yarn run build
      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}